### ISSUE TITLE
TKinter isn't installed by default in Ubuntu 18.XX

### ISSUE THREAD

**Issue by nate2014jatc** [Trapdoor-NX/switch-launcher#1]
Hello,
I would suggest adding a line in the Requirements section stating "You should check to be sure TKinter is installed on your system."

Thank you for your hard work!
(this was the only thing I had an issue with)

**Comment by ksmit799** [comment]
This has been fixed in 096f186.

Thanks for the issue!

**Comment by nate2014jatc** [comment]
I'm glad to help :)
